# this is to avoid annoyances changing modes in vim after pressing ESC
set -sg escape-time 20
# This allows tmux to write to the global clipboard when in copy mode
set -s copy-command 'wl-copy -np'
# these are settings that facilitate iamge previews in yazi
set -g allow-passthrough on
set -ga update-environment TERM
set -ga update-environment TERM_PROGRAM
